# Generated by Django 5.2.8 on 2025-11-24 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametroSimulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del parámetro')),
                ('estacion', models.CharField(blank=True, choices=[('verano', 'Verano'), ('otono', 'Otoño'), ('invierno', 'Invierno'), ('primavera', 'Primavera')], max_length=20, null=True, verbose_name='Estación del año')),
                ('factor_ajuste', models.DecimalField(decimal_places=2, default=1.0, help_text='Multiplicador para ajustar tiempos/pérdidas (1.0 = sin cambio)', max_digits=5, verbose_name='Factor de ajuste')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Parámetro de Simulación',
                'verbose_name_plural': 'Parámetros de Simulación',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='TipoAlga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del tipo de alga')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('tiempo_cultivo_dias', models.IntegerField(help_text='Días necesarios para que el alga madure', verbose_name='Tiempo de cultivo (días)')),
                ('porcentaje_perdida', models.DecimalField(decimal_places=2, help_text='Porcentaje de pérdida durante el cultivo (ej: 20 para 20%)', max_digits=5, verbose_name='Porcentaje de pérdida (%)')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Alga',
                'verbose_name_plural': 'Tipos de Algas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Simulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toneladas_deseadas', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Toneladas deseadas')),
                ('fecha_objetivo', models.DateField(verbose_name='Fecha objetivo de entrega')),
                ('toneladas_a_plantar', models.DecimalField(decimal_places=2, help_text='Cantidad que se debe plantar considerando las pérdidas', max_digits=10, verbose_name='Toneladas a plantar')),
                ('fecha_inicio_cultivo', models.DateField(verbose_name='Fecha de inicio de cultivo')),
                ('dias_cultivo', models.IntegerField(verbose_name='Días de cultivo necesarios')),
                ('notas', models.TextField(blank=True, verbose_name='Notas adicionales')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulaciones', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('tipo_alga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulacion.tipoalga', verbose_name='Tipo de alga')),
            ],
            options={
                'verbose_name': 'Simulación',
                'verbose_name_plural': 'Simulaciones',
                'ordering': ['-creado_en'],
            },
        ),
    ]
